import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppBar } from "@/components/AppBar/AppBar";
import StoreProvider from "@/lib/store/StoreProvider";
import { ThemeProvider } from "@/components/Theme/ThemeProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const themeInitScript = `
  (function () {
    try {
      const theme = localStorage.getItem('theme') || 'light';
      document.documentElement.dataset.theme = theme;
    } catch (_) {}
  })();
`;


  return (
    <html lang="en">
      <head><script dangerouslySetInnerHTML={{ __html: themeInitScript }} /></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-[var(--background)]`}
      >

        <StoreProvider>
          <ThemeProvider>
            <AppBar />
            {children}
          </ThemeProvider>
        </StoreProvider>

      </body>
    </html>
  );
}
